### ISSUE TITLE
Output of the passthrough sample is incorrect

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#175]
**Description:**
Output of the passthrough sample is incorrect

https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/passthrough/passthrough.client.sh

**Comment by dilinisg** [comment]
PR sent : https://github.com/ballerina-platform/ballerina-examples/pull/174

**Comment by uthaiyashankar** [comment]
merged.

**Comment by shavantha** [comment]
The passthrough sample seems to be broken

setup
======
ballerina-platform-0.970.0-beta3 19th April 2018

steps
========
./ballerina run ~/products/ballerina/ballerina-examples/examples/passthrough

output
==========
```
error: ./passthrough.bal:7:10: unknown type 'SimpleClient'
error: ./passthrough.bal:7:1: incompatible types: requires an object type
error: ./passthrough.bal:7:37: invalid literal for type 'other'
error: ./passthrough.bal:22:30: invalid action invocation, expected an endpoint
compilation contains errors
```

**Comment by uthaiyashankar** [comment]
This is fixed.
