### ISSUE TITLE
[Sample] errors in invoking the worker-interaction sample :ballerina-0.970.0-beta1-SNAPSHOT

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#178]
when invoking the worker-interaction sample the below error is thrown
openjdk version "1.8.0_162"
ubuntu 16.04

[w1] iw: 200 kw: 5.44
examples/worker-interaction/worker-interaction.bal 
error: ./worker-interaction.bal:15:41: unreachable pattern: preceding patterns are too general or the pattern ordering is not correct
error: ./worker-interaction.bal:29:43: unreachable pattern: preceding patterns are too general or the pattern ordering is not correct
compilation contains errors

**Comment by shavantha** [comment]
checked with beta6 and the response is as 
```
[w1 -> w2] i: 100 k: 2.34
[w2 <- w1] iw: 100 kw: 2.34
[w2 -> w1] jw: {"name":"Ballerina"}
[w1 <- w2] j: {"name":"Ballerina"}
```

**Comment by uthaiyashankar** [comment]
Resolving as per last comment.
