### ISSUE TITLE
[Sample] transform-json sample fails :ballerina-0.970.0-beta1

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#181]
openjdk version "1.8.0_162"
ubuntu 16.04

transform-json sample fails when invoking

./ballerina run examples/transform-json/transform-json.bal

```
-=-----------
error: ./transform-json.bal:11:1: invalid token 'transformer'
compilation contains errors

```

**Comment by uthaiyashankar** [comment]
We need to remove tranform sample.

**Comment by uthaiyashankar** [comment]
This sample is removed.
