### ISSUE TITLE
[Sample] character-i-o.bal sample fails :ballerina-0.970.0-beta1-SNAPSHOT

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#182]
character-i-o sample fails since a required file is not available

openjdk version "1.8.0_162"
ubuntu 16.04

issue the command
./ballerina run examples/character-i-o/character-i-o.bal
```

error: ballerina.runtime:CallFailedException, message: call failed
	at .:main(character-i-o.bal:76)
caused by error, message: failed to open file: file not found: ./files/sample.txt
	at ballerina.io:openFile(<native>)

```

**Comment by uthaiyashankar** [comment]
You need to run inside character-i-o folder. 

The instruction says, following, which assumes you are inside the folder. 
ballerina run character-i-o.bal

**Comment by shavantha** [comment]
verified by running the sample from within character-i-o.bal
