### ISSUE TITLE
[Sample]Throw sample fails :ballerina-0.970.0-beta1-SNAPSHOT

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#185]
run the command
./ballerina run /home/shavantha/products/ballerina/ballerina-examples/throw/throw.bal

openjdk version "1.8.0_162"
ubuntu 16.04

```
examples/throw/throw.bal 
Record ID: 1, value: record1
error: ballerina.runtime:CallFailedException, message: call failed
	at .:main(throw.bal:32)
caused by error, message: record is null
	at .:readRecord(throw.bal:17)
```

**Comment by dilinisg** [comment]
Output should be updated in [1] with the above output

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/throw/throw.sh

**Comment by uthaiyashankar** [comment]
Output updated.

**Comment by shavantha** [comment]
verified the output
