### ISSUE TITLE
[Sample] The sample decode-nested-bodyparts-in-multipart description is not complete 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#194]
The sample decode-nested-bodyparts-in-multipart description is not complete. When we run the bal file the sample starts listing but what is the call to invoke this sample should go into the samples sh file or the description file

**Comment by arukshani** [comment]
Nested body part code snippet has been moved here https://github.com/ballerina-platform/ballerina-examples/tree/master/examples/response-with-multiparts and the call to invoke the sample can be found in here https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/response-with-multiparts/response_with_multiparts.client.out
