### ISSUE TITLE
[Sample] http-client connectior sample throws a SSL Engine closed already error

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#199]
**Environment**
Oracle jdk 1.8.0_121
ballerina-0.970.0-beta1-SNAPSHOT

**Description:**

Run the below command to execute the sample

./ballerina run /home/shanika/WSO2/ballerina-cmd4-BBEx/ballerina-examples/examples/http-client-connector/http-client-connector.bal

Observed the following output

GET request:
{"args":{"test":"123"},"headers":{"host":"postman-echo.com","user-agent":"ballerina/0.970.0-beta1-SNAPSHOT","x-forwarded-port":"443","x-forwarded-proto":"https"},"url":"https://postman-echo.com/get?test=123"}

POST request:
{"args":{},"data":"POST: Hello World","files":{},"form":{},"headers":{"host":"postman-echo.com","content-length":"17","content-type":"text/plain","user-agent":"ballerina/0.970.0-beta1-SNAPSHOT","x-forwarded-port":"443","x-forwarded-proto":"https"},"json":null,"url":"https://postman-echo.com/post"}

PUT request:
{"args":{},"data":"{\"method\":\"PUT\",\"payload\":\"Hello World\"}","files":{},"form":{},"headers":{"host":"postman-echo.com","content-length":"40","content-type":"text/plain","user-agent":"ballerina/0.970.0-beta1-SNAPSHOT","x-forwarded-port":"443","x-forwarded-proto":"https"},"json":null,"url":"https://postman-echo.com/put"}

PATCH request:
{"args":{},"data":"{}","files":{},"form":{},"headers":{"host":"postman-echo.com","content-length":"2","content-type":"text/plain","user-agent":"ballerina/0.970.0-beta1-SNAPSHOT","x-forwarded-port":"443","x-forwarded-proto":"https"},"json":null,"url":"https://postman-echo.com/patch"}

DELETE request:
{"args":{},"data":"DE","files":{},"form":{},"headers":{"host":"postman-echo.com","content-length":"2","content-type":"text/plain","user-agent":"ballerina/0.970.0-beta1-SNAPSHOT","x-forwarded-port":"443","x-forwarded-proto":"https"},"json":null,"url":"https://postman-echo.com/delete"}
**SSLEngine closed already**

**Comment by Bhashinee** [comment]
Not reproducible in the latest version.
