### ISSUE TITLE
http-circuit-breaker sample is giving errors in Mac

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-examples#204]
**Description:**
http-circuit-breaker sample is giving errors in Mac

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/High
Affected/ballerina-0.970.0-beta1-SNAPSHOT.zip

**Affected Product Version:**
ballerina-0.970.0-beta1-SNAPSHOT.zip - Build from 18-04-2018

**OS, DB, other environment details and versions:**    
OS-macOS high sierra
JDK-18.0.152
ballerina-0.970.0-beta1-SNAPSHOT.zip - Build from 18-04-2018

**Steps to reproduce:**
Took the latest build of ballerina runtime and extract it (Build 18-04-2018)
Took the latest build from the sample repo
Run http-circuit-breaker sample and below error could see in the console

**Results:**

`error: ./http-circuit-breaker.bal:16:13: undefined field 'timeWindowMillis' in struct 'ballerina.http:RollingWindow'
error: ./http-circuit-breaker.bal:17:13: undefined field 'bucketSizeMillis' in struct 'ballerina.http:RollingWindow'
error: ./http-circuit-breaker.bal:20:9: undefined field 'resetTimeMillis' in struct 'ballerina.http:CircuitBreakerConfig'
compilation contains errors
`

**Comment by uthaiyashankar** [comment]
this is fixed.
