### ISSUE TITLE
[Sample] Compilation errors in xml function sample in ballerina-0.970.0-beta1-SNAPSHOT

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#208]
**Environment**
Oracle jdk 1.8.0_121
ballerina-0.970.0-beta1-SNAPSHOT

**Description:**
Run the below command to execute the sample

./ballerina run /home/shanika/WSO2/ballerina-cmd4-BBEx/ballerina-examples/examples/xml-functions/xml-functions.bal

Obeserved the below exception

error: ./xml-functions.bal:11:16: incompatible types: 'string' cannot be convert to 'xml'
compilation contains errors

**Comment by uthaiyashankar** [comment]
This is fixed.
