### ISSUE TITLE
[Sample] Compilation errors in running hub.bal file in websub-remote-hub-sample

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#211]
**Environment**
Oracle jdk 1.8.0_121
ballerina-0.970.0-beta1-SNAPSHOT

**Description:**

**Run the below command to execute the hub.bal file 1st as mentioned in the description** 
./ballerina run /home/shanika/WSO2/ballerina-cmd4-BBEx/ballerina-examples/examples/websub-remote-hub-sample/hub.bal

Observed the below error
error: ballerina/websub/subscriber_service_endpoint.bal:81:30: incompatible types: expected 'ballerina.http:Filter', found 'ballerina.http:Filter|error'
error: ballerina/websub/subscriber_service_endpoint.bal:147:79: A matching pattern cannot be guaranteed for types '[ballerina.http:AuthConfig]'
error: ballerina/websub/commons.bal:187:54: unreachable pattern: preceding patterns are too general or the pattern ordering is not correct
error: ballerina/websub/hub_client_connector.bal:140:57: unreachable pattern: preceding patterns are too general or the pattern ordering is not correct
error: ballerina/websub/hub_client_connector.bal:155:69: unreachable pattern: preceding patterns are too general or the pattern ordering is not correct
error: ballerina/websub/hub_client_connector.bal:156:73: unreachable pattern: preceding patterns are too general or the pattern ordering is not correct
compilation contains errors

Please mention in the description file if there is some other environment settings are needed to run this sample other than running the .bal files in the specified order.

**Comment by uthaiyashankar** [comment]
This is fixed.
