### ISSUE TITLE
compilation errors when running the jms-queue-message-producer-transaction sample: ballerina-0.970.0-beta1-SNAPSHOT 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#213]
./ballerina run  jms-queue-message-producer-transaction/jms-queue-message-producer-transaction.bal 
```
error: ./jms-queue-message-producer-transaction.bal:26:9: variable assignment is required
compilation contains errors
```

**Comment by uthaiyashankar** [comment]
this is fixed

**Comment by shavantha** [comment]
verified with the build ballerina-0.970.0-beta13-SNAPSHOT response "2018-04-23 14:06:10,289 INFO  [] - Message successfully sent. "
