### ISSUE TITLE
[Sample] Invalid token error in running transformers sample

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#220]
**Environment**
Oracle jdk 1.8.0_121
ballerina-0.970.0-beta1-SNAPSHOT

**Description:**
Run the below command to execute the sample

./ballerina run /home/shanika/WSO2/ballerina-cmd4-BBEx/ballerina-examples/examples/transformers/transformers.bal

Observed the below error

error: ./transformers.bal:20:1: invalid token 'transformer'
compilation contains errors

**Comment by uthaiyashankar** [comment]
Same: https://github.com/ballerina-platform/ballerina-examples/issues/181

We need to remove these samples.

**Comment by uthaiyashankar** [comment]
This sample is removed.
