### ISSUE TITLE
Error invoking the websocket-chat-application

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#221]
Pack - Tools build on 18/04/2018
Oracle JDK - "1.8.0_161"
Windows 7

**Description:**
Error invoking the websocket-chat-application.

![image](https://user-images.githubusercontent.com/1845370/38924715-986dda3e-42f5-11e8-840f-07d99033365c.png)

**Comment by uthaiyashankar** [comment]
This is working as expected in mac. May be a windows specific issue.

**Comment by irunika** [comment]
Checked with Windows 7 & 10
Oracle JDK 1.8.0_172
ballerina RC 0.980.0

Works fine without any issue
