### ISSUE TITLE
[Sample] Fork Join condition some sample fails in ballerina-0.970.0-beta1-SNAPSHOT

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#226]
**Environment**
Oracle jdk 1.8.0_121
ballerina-0.970.0-beta1-SNAPSHOT

**Description:**
Run the below command
 ./ballerina run /home/shanika/WSO2/ballerina-cmd4-BBEx/ballerina-examples/examples/fork-join-condition-some/fork-join-condition-some.bal

Obesrved below error
[w1] i: 23 s: Colombo
[join-block] iW1: 23 sW1: Colombo
fatal error: cannot find key 'w2'
[w2] f: 10.344
error: error, message: cannot find key 'w2'
	at .:main(fork-join-condition-some.bal:34)

**Comment by uthaiyashankar** [comment]
This is fixed. Please check and reopen.
