### ISSUE TITLE
error when runnign config-api sample : ballerina-0.970.0-beta1-SNAPSHOT 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#228]
i created a custom-config-file-name.conf file with contents as "john has RW access" when I run with a command as  [1] the sample returns an error as 

java version "1.8.0_131"
ubuntu 16.04

[1]
` ballerina run home/shavantha/products/ballerina/ballerina-examples/examples/config-api/config-api.bal --config /home/shavantha/products/ballerina/ballerina-examples/examples/config-api/custom-config-file-name.conf`

[2]
```
', ' 1:6 extraneous input 'R' expecting {'	', '
', ' ', '='}
```

**Comment by uthaiyashankar** [comment]
This is working as expected. Please have a look
