### ISSUE TITLE
[sample] the secured-hello-world-service-with-basic-auth fails with compilation errors  : ballerina-0.970.0-beta1-SNAPSHOT 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#230]
the secured-hello-world-service-with-basic-auth fails with compilation errors

Oracle jdk 1.8.0_121
ballerina-0.970.0-beta1-SNAPSHOT

run command 
./ballerina run ballerina/ballerina-examples/examples/secured-hello-world-service-with-basic-auth/secured-hello-world-service-with-basic-auth.bal 

```
error: ./secured-hello-world-service-with-basic-auth.bal:7:10: undefined package 'endpoints'
error: ./secured-hello-world-service-with-basic-auth.bal:7:1: incompatible types: requires an object type
error: ./secured-hello-world-service-with-basic-auth.bal:7:35: invalid literal for type 'other'
error: ./secured-hello-world-service-with-basic-auth.bal:35:33: endpoint type ep does not support service registration
error: ./secured-hello-world-service-with-basic-auth.bal:31:1: undefined annotation 'Config'
error: ./secured-hello-world-service-with-basic-auth.bal:43:5: undefined annotation 'Config'
error: ./secured-hello-world-service-with-basic-auth.bal:47:29: invalid usage of record literal with type 'ballerina.http:Response'
compilation contains errors
```

**Comment by kavithasub** [comment]
Env:
rhel 7.3 | oracle jdk 1.8.0_161
ballerina-platform-0.970.0-beta4

This sample failing with 401.
Steps to recreate:
>[root@ballerinaonrethat3 cloud-user]# bash userstore-generator.sh -u kavitha -p kavitha123 -g testgroup100
>[root@ballerinaonrethat3 cloud-user]# bash permissionstore-generator.sh -s scope100 -g testgroup100
>[root@ballerinaonrethat3 cloud-user]# ./buildpack/ballerina-platform-0.970.0-beta4/bin/ballerina run secured-hello-world-service-with-basic-auth.bal

>kavitha@kavitha-ThinkPad-X1-Carbon-3rd:~$ curl -vk -H "Authorization: Basic a2F2aXRoYTprYXZpdGhhMTIz" https://192.168.48.30:9090/hello/sayHello

Output:
[unauthorize.txt](https://github.com/ballerina-platform/ballerina-examples/files/1931572/unauthorize.txt)

**Comment by uthaiyashankar** [comment]
This is working now. 

@kavithasub the sample tells to create a config file. With that, it works.. not sure whether the steps you followed were previous instructions. If this instructions are somewhere, please reopen the issue.
