### ISSUE TITLE
Error invoking the websocket-basic-sample 

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#231]
Pack - Tools build on 18/04/2018
Oracle JDK - "1.8.0_161"
Windows 7

**Description:**
Error invoking the websocket-basic-sample 

![image](https://user-images.githubusercontent.com/1845370/38929906-d9b4224a-4305-11e8-87c2-5cf2079e7546.png)

**Comment by irunika** [comment]
Checked with Windows 7 & 10
Oracle JDK 1.8.0_172
ballerina RC 0.980.0

Works fine without any issue
