### ISSUE TITLE
iterable-operations sample fails to execute  : ballerina-0.970.0-beta1-SNAPSHOT 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#234]
run the sample as 
./ballerina run ~/products/ballerina/ballerina-examples/examples/iterable-operations/iterable-operations.bal

Oracle jdk 1.8.0_121
ballerina-0.970.0-beta1-SNAPSHOT

```
error: ./iterable-operations.bal:28:50: unreachable pattern: preceding patterns are too general or the pattern ordering is not correct
compilation contains errors
```

**Comment by uthaiyashankar** [comment]
This is fixed.

**Comment by shavantha** [comment]
verified with the build ballerina-0.970.0-beta13-SNAPSHOT
