### ISSUE TITLE
Issues in the grpc-secured-unary sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#238]
Pack - Tools build on 18/04/2018
Oracle JDK - "1.8.0_161"
Windows 7

**Description:**
The following error is thrown when running the sample

```
ballerina: initiating service(s) in 'grpc-secured-unary.bal'
error: error, message: method name should be prefixed with service name and separated with '/'. Expected service name: 'HelloWorld'. Actual fully qualifed method name: 'HelloWorld\hello'.
        at ballerina.grpc:register(<native>)

```

Also, mention the steps to run the sample and expected output in the sample description

**Comment by uthaiyashankar** [comment]
This is working now. Please reopen if it is failing yet.
