### ISSUE TITLE
Error running the grpc-server-streaming sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#239]
Pack - Tools build on 18/04/2018
Oracle JDK - "1.8.0_161"
Windows 7

**Description:**
Error running the grpc-server-streaming sample

```
ballerina: initiating service(s) in 'grpc-server-streaming.bal'
error: error, message: method name should be prefixed with service name and separated with '/'. Expected service name: 'HelloWorld'. Actual fully qualifed method name: 'HelloWorld\lotsOfReplies'.
        at ballerina.grpc:register(<native>)
```

Also, mention the steps to run the sample and expected output in the sample description

**Comment by uthaiyashankar** [comment]
This is working as expected. Please reopen if the problem is still there.
