### ISSUE TITLE
Issues in the grpc-unary-non-blocking sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#242]
Pack - Tools build on 18/04/2018
Oracle JDK - "1.8.0_161"
Windows 7

**Issues:**

1. The following error is thrown when running the sample
```
ballerina: initiating service(s) in 'grpc-unary-service.bal' error: error, message: method name should be prefixed with service name and separated with '/'. Expected service name: 'HelloWorld'. Actual fully qualifed method name: 'HelloWorld\hello'.
        at ballerina.grpc:register(<native>)
```

2. Does not mention the steps to run the sample or the expected output in the sample description
3. The sample name grpc-unary-service.bal should be changed to grpc-unary-non-blocking-sample to be consistent with other samples. Also, the

**Comment by uthaiyashankar** [comment]
These are fixed.
