### ISSUE TITLE
error in running ballerina programs after installing the distribution ballerina-0.970.0-beta1 of 18th April 2018

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#247]
after installing the distribution if we issue the command ballerina run hello-world/ we get the below error[1]. however, if we go into /opt/ballerina/ballerina-0.970.0-beta1/bin and issue the command ./ballerina run ballerina-examples/examples/hello-world the sample works as expected

preconditions
1.remove all java installations 
2.install the ballerina distribution of 18th April 2018
3.go into ballerina-examples/examples folder and issue the command ballerina run hello-world/

```
error: hello-world:0.0.1/hello-world-test.bal:19:10: incompatible types: expected 'string', found 'any[]'
compilation contains errors
```

**Comment by shavantha** [comment]
Scenario 1
Go to path` ballerina-examples/examples` and issue command` ballerina run hello-world/`
Response `error: hello-world:0.0.1/hello-world-test.bal:19:10: incompatible types: expected 'string', found 'any[]'`

Scenario 2:
Go to path` ballerina-examples/examples` and issue command` ballerina run hello-world/hello-world.bal` Response `ballerina: cannot find file 'hello-world/hello-world.bal'`

**Comment by uthaiyashankar** [comment]
This is fixed now.
