### ISSUE TITLE
Cannot run with ballerina command outside the ballerina_home/bin directory

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#248]
**Description:**
Cannot run samples with ballerina command outside the ballerina_home/bin directory

**Affected Product Version:**
Pack - Tools build on 18/04/2018

**OS, DB, other environment details and versions:**    
Oracle JDK - "1.8.0_161"
Windows 7

**Steps to reproduce:**
1. Run a sample from ballerina_home/bin directory
`ballerina run <pathToSamples>/sample.bal`
The sample will execute successfully

2. Run a sample from outside ballerina_home/bin directory 
eg: move to C:\ directory and run,
`ballerina run <pathToSamples>/sample.bal`

**Issues:**
The following error will be logged which is wrong. Should be able to run with ballerina command from any directory

`ballerina: main function not found in 'hello-world.bal'`

**Comment by uthaiyashankar** [comment]
This is working as expected in mac. May be a windows specific issue.

**Comment by dilinisg** [comment]
Verified the issue against Ballerina 0.970.0 release and observed that it has been partly fixed.

**Current Issue**
ballerina command is working inside C drive, however it is not working in other drives.

**Comment by NipunaRanasinghe** [comment]
Closing hence this issue is already fixed
