### ISSUE TITLE
http-sessions sample fails

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-examples#253]
Env: 
rhel 7.3 | oracle jdk 1.8.0_161
"ballerina-platform-0.970.0-beta1" installer

**Description:**
http-sessions sample fails with below error when running against "ballerina-platform-0.970.0-beta1" installer
>[root@ballerinaonrethat3 examples]# ballerina run http-sessions/http-sessions.bal 
error: ./http-sessions.bal:18:9: unknown type 'Session'
error: ./http-sessions.bal:18:32: undefined function 'createSessionIfAbsent' in struct 'ballerina.http:Request'
error: ./http-sessions.bal:39:9: unknown type 'Session'
error: ./http-sessions.bal:39:32: undefined function 'getSession' in struct 'ballerina.http:Request'
error: ./http-sessions.bal:57:9: unknown type 'Session'
error: ./http-sessions.bal:57:32: undefined function 'getSession' in struct 'ballerina.http:Request'
compilation contains errors

**Suggested Labels:**
Type/bug
Priority/Highest

**Comment by uthaiyashankar** [comment]
We need to remove session sample.

**Comment by uthaiyashankar** [comment]
Duplicate: https://github.com/ballerina-platform/ballerina-examples/issues/195
