### ISSUE TITLE
Output of the Map sample is incorrect

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#254]
Pack - Platform - beta1
Oracle JDK - "1.8.0_161"
Windows 7

**Description:**
The following is the received output.
```
{"line1":"No. 20", "line2":"Palm Grove", "city":"Colombo 03", "country":"Sri Lanka"}
Sri Lanka
Colombo 03
{"line1":"No. 20", "line2":"Palm Grove", "city":"Colombo 03", "country":"Sri Lanka", "postalCode":"00301"}
["line1", "line2", "city", "country", "postalCode"]
5
{"line1":"No. 20", "line2":"Palm Grove", "city":"Colombo 03", "country":"Sri Lanka"}
```

The following is in [1]
`["country", "city", "postalCode", "line2", "line1"]`

instead
`["line1", "line2", "city", "country", "postalCode"]`

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/maps/maps.sh

**Comment by dilinisg** [comment]
PR: https://github.com/ballerina-platform/ballerina-examples/pull/318

**Comment by uthaiyashankar** [comment]
Merged and fixed.
