### ISSUE TITLE
Output of the constrained json sample is incorrect

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#257]
Pack - Platform - beta1
Oracle JDK - "1.8.0_161"
Windows 7

**Description:**
Output of the constrained json sample is incorrect

**Output received:**
```
{"name":"Jon","age":25,"city":"Colombo"}
{"name":"Jon","age":25,"city":"Colombo"}
```

**Output in [1]:**
{"name":"Jon","age":25,"city":"Colombo"}
{"name":"Jon","age":25,"city":"Colombo","profession":"Software Engineer"}

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/constrained-json/constrained-json.sh

**Comment by MaryamZi** [comment]
Closing since the output of the constrained JSON sample is the following, as expected:
```
{"name":"Jon","age":25,"city":"Colombo"}
Software Engineer
```

Tested with 0.975.1
