### ISSUE TITLE
Output of the type-conversion sample is incorrect

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#261]
**Description:**
Missed the last line of the output received in [1]

Actual Output
```
10
error: 'string' cannot be converted to 'int'
5
1
true
true
3.14
```

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/type-conversion/type-conversion.sh

**Affected Product Version:**
Ballerina Platform - beta1

**OS, DB, other environment details and versions:**    
In-built JAVA
Windows 7

**Comment by shavantha** [comment]
same on ubuntu setup using openjdk version "1.8.0_162"

**Comment by dilinisg** [comment]
PR : https://github.com/ballerina-platform/ballerina-examples/pull/318

**Comment by uthaiyashankar** [comment]
merged and fixed.
