### ISSUE TITLE
Compilation error in the observe-tracing sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#264]
**Description:**
Compilation error in the observe-tracing sample

```
error: .\observe-tracing.bal:39:68: unreachable pattern: preceding patterns are too general or the pattern ordering is not correct
compilation contains errors
```

**Affected Product Version:**
Ballerina Platform - beta1

**OS, DB, other environment details and versions:**    
In-built JAVA
Windows 7

**Comment by uthaiyashankar** [comment]
This sample is removed
