### ISSUE TITLE
Output of the async sample is incorrect

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#267]
**Description:**

Additional "17839763" is included in the output in [1]

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/async/async.sh

**Affected Product Version:**
Ballerina Platform - beta1

**OS, DB, other environment details and versions:**    
In-built JAVA
Windows 7

**Comment by uthaiyashankar** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-examples/pull/375
