### ISSUE TITLE
grpc-secured-unary sample fails when we run the client

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#274]
grpc-secured-unary sample fails

Ubuntu 16.04
Embedded java

preconditions`
1.the command `ballerina init `was run within the `client `folder within` grpc-secured-unary  
steps
1.run the command ballerina run grpc-unary-service.bal
2.run the command ballerina run client

```
error: ballerina.runtime:CallFailedException, message: call failed
	at client:main(helloWorld.sample.client.bal:14)
caused by ballerina.runtime:NullReferenceException
	at client:hello(helloWorld.pb.bal:28)

```

**Comment by daneshk** [comment]
@shavantha we tested gRPC secured sample, but didn't fail for me. Running `ballerina init` within client directory is not correct. Here `client` is ballerina package. we need to run within parent directory. 

Can you check this again

**Comment by daneshk** [comment]
Closing this issue, since we cannot reproduce the issue. And also we did some significant change in this area.
Please reopen the issue if you encounter this issue again.
