### ISSUE TITLE
sql-queries-on-tables sample fails

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-examples#275]
Env:
rhel 7.3 | oracle jdk 1.8.0_161
"ballerina-platform-0.970.0-beta1" installer

**Description:**
sql-queries-on-tables.sh sample fails with below error
>[root@ballerinaonrethat3 examples]# ballerina run sql-queries-on-tables/sql-queries-on-tables.bal
The personTable: {data: [{id:1, age:25, salary:1000.5, name:"jane", married:true}, {id:2, age:26, salary:1050.5, name:"kane", married:false}, {id:3, age:27, salary:1200.5, name:"jack", married:true}, {id:4, age:28, salary:1100.5, name:"alex", married:false}]}
The orderTable: {data: [{personId:1, orderId:1234, items:"pen, book, eraser", amount:34.75}, {personId:1, orderId:2314, items:"dhal, rice, carrot", amount:14.75}, {personId:2, orderId:5643, items:"Macbook Pro", amount:2334.75}, {personId:3, orderId:8765, items:"Tshirt", amount:20.75}]}
table<Person> personTableCopy = from personTable select *;
personTableCopy: {data: [{id:1, age:25, salary:1000.5, name:"jane", married:true}, {id:2, age:26, salary:1050.5, name:"kane", married:false}, {id:3, age:27, salary:1200.5, name:"jack", married:true}, {id:4, age:28, salary:1100.5, name:"alex", married:false}]}
error: error, message: error in executing statement : CREATE TABLE TABLE_PERSON_3 AS select *  from (select * from TABLE_PERSON_0) order by salary null error:Syntax error in SQL statement "CREATE TABLE TABLE_PERSON_3 AS SELECT *  FROM (SELECT * FROM TABLE_PERSON_0) ORDER BY SALARY NULL[*] "; SQL statement:
CREATE TABLE TABLE_PERSON_3 AS select *  from (select * from TABLE_PERSON_0) order by salary null [42000-175]
	at queryTableWithoutJoinClause(<native>)

**Suggested Labels:**
Type/bug
Priority/Highest

**Comment by kavithasub** [comment]
Observed the issue with "order by" - Query2. When commenting the query2 as below other queries are working fine.
> // 2. Query all records in ascending order of salary.
   // table<Person> orderedPersonTableCopy = from personTable
   //                                      select * order by salary;
  //  io:println("table<Person> orderedPersonTableCopy = from personTable select * order by salary;");
  //  io:print("orderedPersonTableCopy: ");
  //  io:println(orderedPersonTableCopy);

**Comment by shavantha** [comment]
on ubuntu 16.04 the error is
```
ballerina: cannot find file '/home/shavantha/products/ballerina/ballerina-examples/examples/testerina-assertions/testerina-assertions.bal'
les/sql-queries-on-tables/sql-queries-on-tables.bal s/ballerina/platform/ballerina-platform-0.970.0-beta4/bin$ ./ballerina run /home/shavantha/products/ballerina/ballerina-examples/examp 
The personTable: table<Person> {index: [], primaryKey: [], data: [{id:1, age:25, salary:1000.5, name:"jane", married:true}, {id:2, age:26, salary:1050.5, name:"kane", married:false}, {id:3, age:27, salary:1200.5, name:"jack", married:true}, {id:4, age:28, salary:1100.5, name:"alex", married:false}]}
The orderTable: table<Order> {index: [], primaryKey: [], data: [{personId:1, orderId:1234, items:"pen, book, eraser", amount:34.75}, {personId:1, orderId:2314, items:"dhal, rice, carrot", amount:14.75}, {personId:2, orderId:5643, items:"Macbook Pro", amount:2334.75}, {personId:3, orderId:8765, items:"Tshirt", amount:20.75}]}
table<Person> personTableCopy = from personTable select *;
personTableCopy: error: error
	at ballerina.io:println(<native>)
```

**Comment by kavithasub** [comment]
Verified fixed with beta13, hence closing.

@shavantha , you should be navigated to the directory that contains the `.bal` file; check sql-queries-on-tables.sh
