### ISSUE TITLE
Inbound-request-with-multiparts sample fails when invoking

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#277]
**Environment**
ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm (2018/04/19)

**Description:**
Install ballerina platform using ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm installer
Run the below command to execute the sample
Go inside /ballerina-examples/examples/inbound-request-with-multiparts

ballerina run inbound-request-with-multiparts.bal

Obeserved the below exception when invoking with the curl command 

*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9090 (#0)
> POST /multiparts/receivableParts HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 275
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------8b6cb2c447f9c531
> 
< HTTP/1.1 404 Not Found
< content-type: text/plain
< content-length: 81
< server: ballerina/0.970.0-alpha4
< date: Thu, 19 Apr 2018 17:43:21 +0530
* HTTP error before end of send, stop sending
< 
* Closing connection 0
no matching resource found for path : /multiparts/receivableParts , method : POST

**Comment by arukshani** [comment]
This is an outdated sample hence not valid anymore. New sample can be found here https://github.com/ballerina-platform/ballerina-examples/tree/master/examples/request-with-multiparts
