### ISSUE TITLE
when running the command ballerina run client for grpc-server-streaming an error is thrown

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#278]
when running the command ballerina run client for  the error[1] is generated

embedded java
ubuntu16.04

preconditions
convert the client folder as a package by running ballerina init

steps
run ballerina run grpc-server-streaming/
issue command ballerina run client
[1]error
Error reported from server: UNIMPLEMENTED: Method not found: HelloWorld/lotsOfReplies

**Comment by uthaiyashankar** [comment]
This is fixed.
