### ISSUE TITLE
Output is not mentioned in the streams-patterns sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#280]
**Description:**
Output is not mentioned in the streams-patterns sample

Actual output:
```
alertRoomAction function invoked for Room:2 and the action :stop
alertRoomAction function invoked for Room:2 and the action :stop
```

**Affected Product Version:**
Ballerina Platform - beta1

**OS, DB, other environment details and versions:**    
In-built JAVA
Windows 7

**Comment by uthaiyashankar** [comment]
This sample is removed.
