### ISSUE TITLE
Mismatch between the listening port and the Curl port in sample inbound-response-with-multiparts

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#281]
**Environment**
ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm (2018/04/19)

**Description:**
Install ballerina platform using ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm installer
Run the below command to execute the sample
Go inside /ballerina-examples/examples/inbound-response-with-multiparts

ballerina run inbound-response-with-multiparts.bal

Obeserved the below exception when invoking with the curl command

curl: (7) Failed to connect to localhost port 9093: Connection refused

Please note that there is a mismatch between the curl request sending port (9093) and listening port mentioned in the.bal file (9090)

**Comment by dilinisg** [comment]
This sample fails in the below environment

Windows 10
Ballerina platform beta4
Oracle JDK - 1.8.0_171
Examples- with the below PR
https://github.com/ballerina-platform/ballerina-examples/pull/301/files

```
error: .\inbound-response-with-multiparts.bal:7:5: undefined field 'targets' in struct 'ballerina.http:ClientEndpointConfig'
compilation contains errors
```

**Comment by uthaiyashankar** [comment]
This is fixed.
