### ISSUE TITLE
Mismatch in the output of foreach sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#283]
**Description:**
Mismatch in the output of foreach sample [1]

Output received:
```
Iterating over a string array
fruit: apple
fruit: banana
fruit: cherry

Iterating over a map.
letter: a, word: apple
letter: b, word: banana
letter: c, word: cherry

Iterating over a json object

Iterating over a json array

Iterating over a xml
xml at 0 :
<name>Sherlock Holmes</name>
xml at 1 :
<author>Sir Arthur Conan Doyle</author>

Iterating over an integer range
summation from 1 to 10 is :55
```

**Affected Product Version:**
Ballerina Platform - beta1

**OS, DB, other environment details and versions:**    
In-built JAVA
Windows 7

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/foreach/foreach.sh

**Comment by uthaiyashankar** [comment]
This is fixed.
