### ISSUE TITLE
Invokation fails in /outbound-request-with-multiparts sample

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#284]
**Environment**
ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm (2018/04/19)

**Description:**
Install ballerina platform using ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm installer
Run the below command to execute the sample
Go inside /ballerina-examples/examples/outbound-request-with-multiparts

ballerina run outbound-request-with-multiparts.bal

Observed below error in the invokation with the curl command
message:"Connection refused: localhost/127.0.0.1:9090", cause:null, statusCode:502}
Error occurred while sending multipart request!

**Comment by uthaiyashankar** [comment]
This is fixed. Sample is renamed to request-with-multiparts
