### ISSUE TITLE
Output is incorrect in character-i-o sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#290]
**Description:**
Actual output:
```
Started to process the file.
 No of characters written : 5
 No of characters written : 12
 No of characters written : 13
File processing complete.
```

Output in [1]
```
Started to process the file.
 No of characters written : 5
 No of characters written : 12
 No of characters written : 12
File processing complete.
```

**Affected Product Version:**
Ballerina beta 3 nightly

**OS, DB, other environment details and versions:**   
JDK - 1.8.0_171
Windows 10

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/character-i-o/character-i-o.sh

**Comment by uthaiyashankar** [comment]
This is working as expected in Mac. Might be a windows specific issues.
