### ISSUE TITLE
multiple samples fail with undefined field 'targets' in struct with beta 3 and beta4

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#298]
mutual-ssl sample throws errors when executed

openjdk version "1.8.0_162"
ubuntu 16.04
ballerina-platform-0.970.0-beta3

error
```
error: ./mutual-ssl.bal:50:5: undefined field 'targets' in struct 'ballerina.http:ClientEndpointConfig'
compilation contains errors

```

**Comment by shavantha** [comment]
with . https://github.com/ballerina-platform/ballerina-examples/pull/301/ the issues are fixed

**Comment by shavantha** [comment]
samples like observe-tracing still has the issue so will reopen the ticket

**Comment by uthaiyashankar** [comment]
This is fixed now. Can you open separate issues for each sample if there are broken
