### ISSUE TITLE
Compilation error when running the http-forwarded-extension sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#302]
**Description:**
Compilation error when running the http-forwarded-extension sample
```
error: .\http-forwarded-extension.bal:11:5: undefined field 'targets' in struct 'ballerina.http:ClientEndpointConfig'
compilation contains errors
```

**Affected Product Version:**
Ballerina beta 4

**OS, DB, other environment details and versions:**    
JDK - 1.8.0_171
Windows 10

**Comment by uthaiyashankar** [comment]
This is fixed.
