### ISSUE TITLE
Issues in the observe-metrics sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#305]
**Description:**
Output of the observe-metrics sample is wrong
```
---Counter---
count: 0.0
count: 0.0

---Gauge---
gauge: 0.0
gauge: 0.0
gauge: 0.0
gauge: 0.0
current system time in milliseconds: 0.0

---Summary---
count : 0
max: 0.0
mean: 0.0
percentile values: {}

---Timer---
count: 0
max: 0.0 seconds
mean: 0.0 seconds
percentile values: {}
```

**Affected Product Version:**
Ballerina beta 4

**OS, DB, other environment details and versions:**    
JDK - 1.8.0_171
Windows 10

**Comment by uthaiyashankar** [comment]
What is the sample name?

Observe samples are removed, since we removed the observe package.
