### ISSUE TITLE
CallFailedException in websub-inernal-hub sample

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#306]
**Environment**
ballerina-platform-0.970.0-beta4.zip (2018/04/20)
ORACLE jdk 1.8.0_121

**Description:**

Run the below command to execute the sample

./ballerina run /home/shanika/WSO2/ballerina-cmd4-BBEx/ballerina-examples/examples/websub-internal-hub-sample/publisher.bal 

Observed below error

2018-04-20 12:46:04,236 INFO  [] - Starting up the Ballerina Hub Service 
error: ballerina.runtime:CallFailedException, message: call failed
	at .:main(publisher.bal:10)
caused by error, message: native function not available ballerina.sql:SQLClient.call
	at ballerina.websub:startUpHubService(<native>)

**Comment by uthaiyashankar** [comment]
This is working now. Please have a look
