### ISSUE TITLE
compilation error for strings sample: ballerina-platform-0.970.0-beta4

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#308]
The strings sample has compilation errors

setup
ballerina-platform-0.970.0-beta4
openjdk version "1.8.0_162"
ubuntu16.04 

./ballerina run ~/ballerina-examples/examples/strings/strings.bal
```
error: ./strings.bal:84:38: invalid usage of array literal with type 'any'
compilation contains errors

```

**Comment by uthaiyashankar** [comment]
This is fixed.
