### ISSUE TITLE
Compilation error when running the outbound-request-with-multiparts sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#309]
**Description:**
Compilation error observed when running this sample in the following environment

Windows 10
Ballerina platform beta4
Oracle JDK - 1.8.0_171
Examples- with the below PR
https://github.com/ballerina-platform/ballerina-examples/pull/301/files

```
error: .\outbound-request-with-multiparts.bal:7:5: undefined field 'targets' in struct 'ballerina.http:ClientEndpointConfig'
error: .\outbound-request-with-multiparts.bal:37:41: incompatible types: expected 'string', found 'ballerina.file:Path'
compilation contains errors
```

**Comment by uthaiyashankar** [comment]
This is fixed
