### ISSUE TITLE
Compilation error when running the outbound-response-with-multiparts sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#310]
**Description:**
Compilation error when running the outbound-response-with-multiparts sample
```
error: .\outbound-response-with-multiparts.bal:35:40: incompatible types: expected 'string', found 'ballerina.file:Path'
compilation contains errors
```

**Affected Product Version:**
Ballerina platform beta4

**OS, DB, other environment details and versions:**    
Oracle JDK - 1.8.0_171
Windows 10

**Comment by shavantha** [comment]
same error comes on ubuntu checked with beta6

**Comment by uthaiyashankar** [comment]
This is fixed in master.
