### ISSUE TITLE
Mismatch in the output of tables sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-examples#311]
**Description:**
Mismatch in the output of tables sample

Output received:
```
Table Data:table<Employee> {index: [], primaryKey: [], data: [{id:1, name:"Jane", salary:300.5}, {id:2, name:"Anne", salary:100.5}, {id:3, name:"John", salary:400.5}, {id:4, name:"Peter", salary:150.0}]}
Name: Jane
Name: Anne
Name: John
Name: Peter
Average of Low salary:125.25
Deleted row count:2
After Delete:table<Employee> {index: [], primaryKey: [], data: [{id:1, name:"Jane", salary:300.5}, {id:3, name:"John", salary:400.5}]}
JSON:[{"id":1,"name":"Jane","salary":300.5},{"id":3,"name":"John","salary":400.5}]
XML:<results><result><id>1</id><name>Jane</name><salary>300.5</salary></result><result><id>3</id><name>John</name><salary>400.5</salary></result></results>
```

**Affected Product Version:**
Ballerina platform beta4

**OS, DB, other environment details and versions:**    
Windows 10
Oracle JDK - 1.8.0_171

**Comment by uthaiyashankar** [comment]
There are several table samples. Can you point the bal file please?

**Comment by uthaiyashankar** [comment]
I guess, this is ballerina-examples/examples/table/table.bal

The expected output is the same as the output you have mentioned. So, may be it is fixed recently. Can you check and reopen if the problem is still there.
