### ISSUE TITLE
Compilation errors in header based routing sample

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#313]
**Environment**
ballerina-platform-0.970.0-beta4.zip (2018/04/20)
ORACLE jdk 1.8.0_121

**Description:**

Run the below command to execute the sample

 ./ballerina run /home/shanika/WSO2/ballerina-cmd4-BBEx/ballerina-examples/examples/header-based-routing/header-based-routing.bal 

Observed below error

error: ./header-based-routing.bal:9:5: undefined field 'targets' in struct 'ballerina.http:ClientEndpointConfig'
error: ./header-based-routing.bal:17:5: undefined field 'targets' in struct 'ballerina.http:ClientEndpointConfig'
compilation contains errors

**Comment by uthaiyashankar** [comment]
This is fixed in master.
