### ISSUE TITLE
The http-2.0-server-push samples client does not generate the results as given on the out files

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#590]
**Description:**
The http-2.0-server-push samples client does not generate the results as given on the out files

java :1.8.0_161
windows 7 professional
ballerina installer beta17

steps
1.start the ballerina run http_2.0_service.bal 
2.run the  ballerina run http_client.bal  command
Note : no results are generated

**Comment by ldclakmal** [comment]
Tested `http-2.0-server-push` sample with the following conditions and issue was not reproducible. Hence, the issue will be closed.

Ballerina version: 0.980.0
OS: Windows 7 Professional (64-bit)
