### ISSUE TITLE
The http-redirects sample on windows is not correct:beta17

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#592]
The output of the http-redirect sample on windows is not as the .out file

steps 
1.C:\ballerina\ballerina-examples\examples>ballerina run http-redirects

**environment**
java :1.8.0_161
windows 7 professional
ballerina installer beta17

```


Response received for the GET request is : <HTML><HEAD><TITLE> Web Authentication Redirect</TITLE><META http-equiv="Cache-
control" content="no-cache"><META http-equiv="Pragma" content="no-cache"><META http-equiv="Expires" content="-1"><META htt
p-equiv="refresh" content="1; URL=https://guestlogin.wso2.com/login.html?redirect=/v2/59d590762700000a049cd694"></HEAD></H
TML>
```

As per the http-redirects.out file the response should be 
`Response received for the GET request is : Redirect Works!`

C:\ballerina\ballerina-examples\examples>

**Comment by ldclakmal** [comment]
Tested `http-redirects` sample with the following conditions and issue was not reproducible. Hence, the issue will be closed.

Ballerina version: 0.980.0
OS: Windows 7 Professional (64-bit)
