### ISSUE TITLE
Swagger to ballerina example cannot be run as is

### ISSUE THREAD

**Issue by nuwand** [ballerina-platform/ballerina-examples#771]
The url of the service used in the swagger to ballerina example is http://petstore.swagger.io/v1. When a Ballerina service is generated out of this the service attempts to bind to host 'petstore.swagger.io' and fails. It also attempts to start a service on port 80 and therefore fails since port 80 cannot be opened unless in sudo mode.

**Comment by samgnaniah** [comment]
This seems like it is fixed now. Closing this.
