### ISSUE TITLE
Sample output is wrong in Rest Parameters sample

### ISSUE THREAD

**Issue by mpmunasinghe** [ballerina-platform/ballerina-examples#781]
**Description:**
The sample output parameters given in Rest Parameters sample is not the exact result the code produces. Should be updated with 

```
Fruits: 
Fruits: Apples
Available Fruits: Apples
Fruits: Apples, Oranges
Available Fruits: Apples, Oranges, Grapes
Available Fruits: Apples, Oranges, Grapes
Available Fruits: Apples, Oranges, Grapes
```

**Suggested Labels:**
documentation

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-examples/pull/792

**Comment by VijithaEkanayake** [comment]
Verify the sample output and is fixed with https://github.com/ballerina-platform/ballerina-examples/pull/792
