### ISSUE TITLE
[Documentation] Provide environment-specific instructions in "Ballerina by Example" examples

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-examples#803]
**Description:**
Refer the original issue https://github.com/ballerina-platform/ballerina-lang/issues/3419 for more details

**Comment by TylerJewell** [comment]
Adding in `sh` or `./` would create a lot of noise. I think we can assume that a developer will get ballerina setup properly in the setup instructions where we shoudl have a verification command that it works. From thereon out, we can assume that people run `ballerina`.

**Comment by samgnaniah** [comment]
Closing this as per the above comment.
