### ISSUE TITLE
Add sample for SOAP 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-examples#839]
**Description:**

Refer the discussion for more details. 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ballerina-dev/K_Y9pPVpR-Q/ZvBw48OhBgAJ

**Comment by Seralahthan** [comment]
Hi All,

I am working on the Ballerina By Guides doc on "Working with SOAP messages" 
I am planning to cover the following areas
 - Provide security for unsecured SOAP service (Username Token: WS-Security)
 - Create and add a JWT for SOAP request based on Username Token
 - Throttling based on SOAP action - throttle mediator
 - Role-based authorization for a particular user (identified by username) for specific SOAP Action

Let me know if there is any more content to be covered in the Guides.
