### ISSUE TITLE
Defining an Object according to the Documentation

### ISSUE THREAD

**Issue by knightbeat** [ballerina-platform/ballerina-examples#884]
When the exact code given in the example [https://ballerina.io/learn/by-example/objects.html](https://ballerina.io/learn/by-example/objects.html), the compilation contains errors as the following.

error: .\test.bal:3:12: invalid token 'int'
error: .\test.bal:3:19: mismatched input ','. expecting ';'
error: .\test.bal:4:23: mismatched input ','. expecting ';'
error: .\test.bal:5:26: mismatched input ','. expecting ';'
error: .\test.bal:6:45: mismatched input ','. expecting {'but', ';', '?', '+', '-', '*', '/', '^', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '?:'}
error: .\test.bal:7:41: mismatched input ','. expecting {'but', ';', '?', '+', '-', '*', '/', '^', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '?:'}
compilation contains errors

**Suggested Labels:**
Ballerina, Object, Struct

**Suggested Assignees:**

**Affected Product Version:**
Ballerina 0.970.1, Ballerina 0.975.1

**Comment by MaryamZi** [comment]
Tried the sample with Ballerina 0.975.1, but obtained the expected output.

Could you please share the exact source you are running?

**Comment by knightbeat** [comment]
When this issue was raised, the documentation had not been updated. Instead of the notation

type Person object {     
    public {         
        int age,         
        ...
   }

It remained as,
type Person object {     
    public int age,         
    ...   
};

Now the document is up to date and the issue is not there anymore.

**Comment by MaryamZi** [comment]
Object field syntax will be as follows from the next release onward.
```
type Person object {
   public int age,
    ...
};
```
With previous versions, the former would work. 

Closing the issue based on the feedback, since this was due to a temporary documentation issue. Thank you.
