### ISSUE TITLE
gRPC Sample Has No Instructions or Protobuf File

### ISSUE THREAD

**Issue by autodidaddict** [ballerina-platform/ballerina-examples#939]
**Description:**
The gRPC example doesn't give you information on how you're supposed to automatically generate the _pb.bal file. It also doesn't include the `helloworld.proto` file from which the Ballerina file was generated. There's also no instructions on how to share types from a protobuf file like messages - the sample(s) show the server having private types and not using the shared generated file, which differs from how other languages like Go build their services. 

**Suggested Labels:**
documentation tutorial

**Steps to reproduce:**
Follow along from the documentation, create the server file and the client file won't compile because there's no instructions on how to generate it.

**Comment by autodidaddict** [comment]
I was looking at the example files, and it wasn't until later that I found the "by guide". I think if the example's README would point to the relevant guide, this would help document things and create less confusion.

**Comment by daneshk** [comment]
@autodidaddict Thanks for the suggestion. We will work on improving gRPC examples. 
We will add additional steps for 
* How to build proto contract from gRPC service.
* Generate client stub from the proto contract. We have proto-to-ballerina example[1] to describe how to generate client stub. but it is not linked to gRPC examples.

1.https://github.com/ballerina-platform/ballerina-examples/tree/master/examples/proto-to-ballerina

Reopening this issue to track those changes.
